version: "3.8"
services:
  web:
    build: .
    ports:
      - "4000:80"
    environment:
      - NAME=World
    depends_on:
      - redis
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
